### PR TITLE
feat: card component added

### PR DESCRIPTION
**Pull request by mdarif6**
feat: card component added

### CODE REVIEW

**Comment by SJTGSHIVAM** [comment]
img{
}
has border radius 50% this need to be fixed.

**Comment by mdarif6** [comment]
img tag issue has been fixed

**Comment by SJTGSHIVAM** [comment]
Now everything looks good to me.

**Review by SJTGSHIVAM — APPROVED** [review]

**Review by Hnh013 — APPROVED** [review]
code looks good , can approve and merge

**Pull request merged**
